# Riemann Framework
# Copyright (C) 2026 MILAN NIKOLIC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
Type stub for the `mpmath` package.

mpmath ships no `py.typed` marker and no inline annotations. Without this stub
Pylance infers parameter types from the constructors' integer/tuple defaults:

    mpf.__new__(cls, val=(0, 0, 0, 0))   ->  `val: tuple[int, int, int, int]`
    mpc.__new__(cls, real=0, imag=0)     ->  `real: int`, `imag: int`

which then rejects every legitimate call such as `mp.mpc(complex)` or
`mp.mpf(float)` with "argument of type X cannot be assigned to parameter of
type int". This stub declares the permissive signatures mpmath actually
accepts, and covers the small subset of its API the repository uses.
"""

from typing import Any


class mpf:
    def __new__(cls, val: Any = ...) -> "mpf": ...
    def __init__(self, val: Any = ...) -> None: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __neg__(self) -> "mpf": ...
    def __pos__(self) -> "mpf": ...
    def __abs__(self) -> "mpf": ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __int__(self) -> int: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


class mpc:
    def __new__(cls, real: Any = ..., imag: Any = ...) -> "mpc": ...
    def __init__(self, real: Any = ..., imag: Any = ...) -> None: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __neg__(self) -> "mpc": ...
    def __pos__(self) -> "mpc": ...
    def __abs__(self) -> "mpf": ...
    def __complex__(self) -> complex: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def real(self) -> "mpf": ...
    @property
    def imag(self) -> "mpf": ...


class matrix:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __add__(self, other: Any) -> "matrix": ...
    def __sub__(self, other: Any) -> "matrix": ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...


def nstr(x: Any, n: int = ..., **kwargs: Any) -> str: ...
def zeta(s: Any = ...) -> Any: ...
def zetazero(n: Any) -> Any: ...
def gamma(x: Any) -> Any: ...
def almosteq(a: Any, b: Any, abs_eps: Any = ..., rel_eps: Any = ...) -> bool: ...
def isnan(x: Any) -> bool: ...
def re(x: Any) -> Any: ...
def im(x: Any) -> Any: ...
def exp(x: Any) -> Any: ...
def log(x: Any, **kwargs: Any) -> Any: ...
def power(x: Any, y: Any) -> Any: ...
def li(x: Any) -> Any: ...
def sin(x: Any) -> Any: ...
def cos(x: Any) -> Any: ...
def conj(x: Any) -> Any: ...
def isfinite(x: Any) -> bool: ...
def isinf(x: Any) -> bool: ...
def isnormal(x: Any) -> bool: ...


# Module-level constants and the mpmath context (`mp.mp.dps`).
pi: Any
e: Any
mp: Any
