# Riemann Framework
# Copyright (C) 2026 MILAN NIKOLIC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
Affine-reduction gate for candidate dimension-shift maps.

Adapted from the Stage B ("triviality check") idea in an external
`rh_idea_framework` prototype. That framework's observation is worth keeping:
most proposals for a "new operation on the complex numbers" turn out to be an
affine map

    f(s) = a*s + b*conjugate(s) + c        (a, b, c complex constants)

already generated by the operations available in the complex plane. The
functional equation of zeta supplies exactly such a map for free, so an idea
that is affine in `(s, conjugate(s))` is not a new algebraic object.

Scope and honesty
-----------------
This module does not prove or disprove anything about the Riemann Hypothesis.
It answers one narrow question about a candidate formula: is it affine in
`(s, conjugate(s))`? A map that fails this gate is not thereby "correct", and a
map that passes it is not thereby "new" in any deeper sense -- it has only
cleared the cheapest bar. There is deliberately no code path here that returns
a verdict of "proved" or "novel".

Implementation note
-------------------
The original prototype used `sympy` for the symbolic second-derivative test.
This repository depends only on mpmath/numpy/scipy, so this module runs the
same test numerically and exactly instead: for an affine expression the second
differences cancel to floating-point zero, and the three coefficients can be
read off directly. Expressions are parsed by a restricted evaluator, never by
bare `eval`, and only a fixed allowlist of `math`/`cmath` names is visible.
"""

from __future__ import annotations

import cmath
import math
from dataclasses import dataclass

# Coefficients are exact for affine inputs, so a tight tolerance is justified;
# it only has to absorb IEEE-754 round-off from the eight evaluations.
_AFFINE_RELATIVE_TOLERANCE = 1e-9
_AFFINE_TOLERANCE = 1e-9  # retained for the absolute fallback in _name_known_map

# Names an idea expression may reference. `s_conj` is a *formal* independent
# variable standing for conjugate(s); see `parse_expression`.
_ALLOWED_NAMES: dict[str, object] = {
    name: getattr(math, name)
    for name in ("exp", "log", "sqrt", "sin", "cos", "tan", "sinh", "cosh", "tanh", "pi", "e")
}
_ALLOWED_NAMES.update({name: getattr(cmath, name) for name in ("exp", "log", "sqrt", "sin", "cos")})
_ALLOWED_NAMES["abs"] = abs

# Substrings that indicate the expression is not a closed-form map on the
# plane, or is trying to smuggle in behaviour this gate cannot certify.
_FORBIDDEN_SUBSTRINGS = (
    "__",
    "import",
    "lambda",
    "exec",
    "eval",
    "open",
    "zeta",
    "prime",
    "range",
    "for ",
    "while ",
)


class ExpressionError(ValueError):
    """Raised when an idea expression cannot be safely evaluated."""


@dataclass
class AffineReduction:
    """Outcome of the affine-reduction gate for one expression."""

    expression: str
    is_affine: bool
    coefficients: tuple[complex, complex, complex] | None
    known_map: str | None
    explanation: str

    @property
    def clears_gate(self) -> bool:
        """True when the expression is *not* a known affine map."""
        return not self.is_affine


def _check_source(expression: str) -> str:
    if not isinstance(expression, str) or not expression.strip():
        raise ExpressionError("Expression must be a non-empty string.")
    lowered = expression.lower()
    for bad in _FORBIDDEN_SUBSTRINGS:
        if bad in lowered:
            raise ExpressionError(
                f"Expression contains the disallowed token {bad!r}. Only closed-form "
                "arithmetic in 's' and 's_conj' is accepted."
            )
    return expression.strip()


def parse_expression(expression: str):
    """Compile `expression` into a callable of the formal variables `(s, s_conj)`.

    `s` and `s_conj` are treated as *independent* variables, the standard trick
    for separating the holomorphic and antiholomorphic parts of a plane map.
    Callers that want the genuine complex conjugate pass `s.conjugate()`
    explicitly as the second argument.
    """
    source = _check_source(expression)
    try:
        code = compile(source, "<idea-expression>", "eval")
    except SyntaxError as exc:
        raise ExpressionError(f"Could not parse expression {expression!r}: {exc}") from exc

    def evaluate(s_value: complex, s_conj_value: complex) -> complex:
        namespace = dict(_ALLOWED_NAMES)
        namespace["s"] = s_value
        namespace["s_conj"] = s_conj_value
        try:
            result = eval(code, {"__builtins__": {}}, namespace)  # noqa: S307 - restricted namespace
        except Exception as exc:  # noqa: BLE001 - surfaced as ExpressionError
            raise ExpressionError(
                f"Expression {expression!r} failed to evaluate at s={s_value}: {exc}"
            ) from exc
        return complex(result)

    return evaluate


def _name_known_map(a: complex, b: complex, c: complex) -> str | None:
    """Recognise textbook special cases, purely for a readable message."""
    if abs(a) < 1e-12 and abs(b + 1) < 1e-12 and abs(c - 1) < 1e-12:
        return "the functional-equation reflection s -> 1 - conjugate(s)"
    if abs(a - 1) < 1e-12 and abs(b) < 1e-12 and abs(c) < 1e-12:
        return "the identity map"
    if abs(a) < 1e-12 and abs(b - 1) < 1e-12 and abs(c) < 1e-12:
        return "plain complex conjugation"
    if abs(a + 1) < 1e-12 and abs(b) < 1e-12 and abs(c - 1) < 1e-12:
        return "the reflection s -> 1 - s"
    if abs(a) < 1e-12 and abs(b) < 1e-12:
        return "a constant map"
    return None


def _eval_pair(evaluate, u: complex, v: complex) -> complex:
    """Evaluate the expression at `s = u + v`, `s_conj = u - v`."""
    return evaluate(u + v, u - v)


def check_affine_reduction(expression: str) -> AffineReduction:
    """Test whether `expression` is affine in `(s, s_conj)`.

    Substituting `u = (s + s_conj)/2`, `v = (s - s_conj)/2` turns the question
    into: does `g(u, v) := f(u + v, u - v)` have vanishing second differences?
    That holds exactly when `f(s, s_conj) = a*s + b*s_conj + c`. A centred
    second difference of a linear term is `2 * coeff * h^2`, so

        a = [g(h,0) + g(-h,0) - 2 g(0,0)] / (2 h^2)
        b = [g(0,h) + g(0,-h) - 2 g(0,0)] / (2 h^2)
        c = g(0,0)

    Note that the *same* positive sign applies to both `d_uu` and `d_vv`: with
    `s = u + v` and `s_conj = u - v`, a step in `+u` moves both variables
    forward and a step in `+v` moves `s` forward while moving `s_conj`
    backward, which is exactly the direction that reproduces `b`.
    """
    evaluate = parse_expression(expression)

    def g(u: complex, v: complex) -> complex:
        """`g(u,v) = f(u+v, u-v)`, the (holomorphic, antiholomorphic) split."""
        return _eval_pair(evaluate, u, v)

    def centred(pair_one: complex, pair_two: complex, f0: complex) -> complex:
        """`pair_one + pair_two - 2*f0`, accumulated without cancellation."""
        return complex(
            math.fsum([pair_one.real, pair_two.real, -2 * f0.real]),
            math.fsum([pair_one.imag, pair_two.imag, -2 * f0.imag]),
        )

    # Centred second differences at a finite step. For `g` quadratic these are
    # *exact* (no truncation error): writing
    #     g = A u^2 + B u v + C v^2 + D u + E v + F
    # gives d_uu = 2 A h^2, d_vv = 2 C h^2, d_uv = B h^2. Hence they vanish
    # identically exactly when `g` is affine, i.e. exactly when `f` is affine in
    # (s, s_conj). A step of 1e-2 keeps the residual well clear of round-off.
    #
    # Do NOT Richardson-extrapolate these: the O(h^2) "error" term IS the
    # curvature being measured, so extrapolating it away would classify every
    # quadratic as affine.
    step = 1e-2
    f0 = g(0j, 0j)
    d_uu = centred(g(step, 0j), g(-step, 0j), f0)
    d_vv = centred(g(0j, step), g(0j, -step), f0)
    d_uv = complex(
        math.fsum([g(step, step).real, -g(step, 0j).real, -g(0j, step).real, f0.real]),
        math.fsum([g(step, step).imag, -g(step, 0j).imag, -g(0j, step).imag, f0.imag]),
    )

    # Compare against the scale of the values actually sampled, so that an
    # expression quoted in different units (`s*s_conj` versus `1000*s*s_conj`)
    # is classified the same way.
    scale = max(
        abs(v)
        for v in (f0, g(step, 0j), g(-step, 0j), g(0j, step), g(0j, -step), g(step, step))
    )
    threshold = _AFFINE_RELATIVE_TOLERANCE * max(scale, 1.0) * step * step

    is_affine = (
        abs(d_uu) <= threshold and abs(d_vv) <= threshold and abs(d_uv) <= threshold
    )

    if not is_affine:
        return AffineReduction(
            expression=expression,
            is_affine=False,
            coefficients=None,
            known_map=None,
            explanation=(
                "Expression is NON-AFFINE in (s, conjugate(s)): it couples the two "
                "variables multiplicatively or through a nonlinear function. It "
                "clears the affine-reduction gate -- it is not merely a renamed "
                "reflection, rotation, scaling, or translation. This is a necessary "
                "condition for novelty only; nothing about correctness follows."
            ),
        )

    # Coefficients are read in the *original* (s, s_conj) coordinates, not in
    # (u, v): holding s_conj at 0 and stepping s gives f = a*s + c directly.
    f_at_origin = evaluate(0j, 0j)
    a = (evaluate(complex(step, 0), 0j) - f_at_origin) / step
    b = (evaluate(0j, complex(step, 0)) - f_at_origin) / step
    c = f_at_origin

    known = _name_known_map(a, b, c)
    explanation = (
        f"Expression reduces to the affine map f(s) = ({_fmt(a)})*s + "
        f"({_fmt(b)})*conj(s) + ({_fmt(c)}). Every such map is a similarity of the "
        "plane -- a composition of a rotation, a scaling, and a translation -- so it "
        "is not a new algebraic object."
    )
    if known:
        explanation += f" It is {known}."

    return AffineReduction(
        expression=expression,
        is_affine=True,
        coefficients=(a, b, c),
        known_map=known,
        explanation=explanation,
    )


def _fmt(value: complex) -> str:
    """Format a recovered coefficient for display.

    Coefficients come out of finite differences, so they carry round-off at the
    last few digits; snap anything within 1e-9 of a short decimal onto it so
    that messages read `-1` rather than `-1.0000000000000009`.
    """
    real = 0.0 if abs(value.real) < 1e-9 else round(value.real, 10)
    imag = 0.0 if abs(value.imag) < 1e-9 else round(value.imag, 10)
    if imag == 0.0:
        return f"{real:g}"
    if real == 0.0:
        return f"{imag:g}i"
    return f"{real:g}{imag:+g}i"


def fixed_locus_is_critical_line(expression: str = "1 - s_conj", samples: int = 41) -> bool:
    """Check numerically that the fixed locus of `expression` is `Re(s) = 1/2`.

    The claim `sigma(s) = s  <=>  Re(s) = 1/2` is asserted in
    `docs/central_hypothesis.md` and is the whole reason the map is interesting.
    It costs nothing to verify: for a grid of points off the critical line the
    fixed-point equation must fail, and on the line it must hold.

    `expression` is evaluated with genuine complex conjugation, i.e. the map is
    taken as a function of one complex variable.
    """
    evaluate = parse_expression(expression)

    def sigma(z: complex) -> complex:
        return evaluate(z, z.conjugate())

    # `abs(...) > tol` is a Python bool for Python floats, but a numpy scalar
    # comparison would yield `np.bool_`, which a type checker refuses to accept
    # where `bool` is declared (numpy 2.x stubs: `np.isclose` returns
    # `np.bool[builtins.bool]`). Coercing explicitly keeps the declared return
    # type honest regardless of what the expression evaluator returns.
    for index in range(samples):
        t = -3.0 + 6.0 * index / (samples - 1)
        on_line = complex(0.5, t)
        if bool(abs(sigma(on_line) - on_line) > 1e-9):
            return False
        for real_part in (0.25, 0.4, 0.6, 0.75):
            off_line = complex(real_part, t)
            if bool(abs(sigma(off_line) - off_line) < 1e-9):
                return False
    return True
